// Mocks generated by Mockito 5.2.0 from annotations
// in todo_app/test/unit_test/repository/task_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/common/api_client/data_state.dart' as _i2;
import 'package:todo_app/data/local/datasource/task_local_datasource.dart'
    as _i8;
import 'package:todo_app/data/task/request_models/create_task_request.dart'
    as _i6;
import 'package:todo_app/data/task/request_models/update_task_request.dart'
    as _i7;
import 'package:todo_app/data/task/response_models/task_model.dart' as _i5;
import 'package:todo_app/data/task/task_service.dart' as _i3;
import 'package:todo_app/models/task.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDataState_0<T> extends _i1.Fake implements _i2.DataState<T> {}

/// A class which mocks [TaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskService extends _i1.Mock implements _i3.TaskService {
  MockTaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<List<_i5.TaskModel>>> getTasks() =>
      (super.noSuchMethod(Invocation.method(#getTasks, []),
              returnValue: Future<_i2.DataState<List<_i5.TaskModel>>>.value(
                  _FakeDataState_0<List<_i5.TaskModel>>()))
          as _i4.Future<_i2.DataState<List<_i5.TaskModel>>>);
  @override
  _i4.Future<_i2.DataState<_i5.TaskModel>> createTask(
          _i6.CreateTaskRequest? data) =>
      (super.noSuchMethod(Invocation.method(#createTask, [data]),
              returnValue: Future<_i2.DataState<_i5.TaskModel>>.value(
                  _FakeDataState_0<_i5.TaskModel>()))
          as _i4.Future<_i2.DataState<_i5.TaskModel>>);
  @override
  _i4.Future<_i2.DataState<_i5.TaskModel>> updateTask(
          _i7.UpdateTaskRequest? data) =>
      (super.noSuchMethod(Invocation.method(#updateTask, [data]),
              returnValue: Future<_i2.DataState<_i5.TaskModel>>.value(
                  _FakeDataState_0<_i5.TaskModel>()))
          as _i4.Future<_i2.DataState<_i5.TaskModel>>);
  @override
  _i4.Future<_i2.DataState<bool>> deleteTask(String? taskId) =>
      (super.noSuchMethod(Invocation.method(#deleteTask, [taskId]),
              returnValue:
                  Future<_i2.DataState<bool>>.value(_FakeDataState_0<bool>()))
          as _i4.Future<_i2.DataState<bool>>);
}

/// A class which mocks [TaskLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskLocalDatasource extends _i1.Mock
    implements _i8.TaskLocalDatasource {
  MockTaskLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.TaskModel>?> getTasks() =>
      (super.noSuchMethod(Invocation.method(#getTasks, []),
              returnValue: Future<List<_i5.TaskModel>?>.value())
          as _i4.Future<List<_i5.TaskModel>?>);
  @override
  _i4.Future<void> setTasks(List<_i9.Task>? tasks) =>
      (super.noSuchMethod(Invocation.method(#setTasks, [tasks]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> updateTask(_i9.Task? task) =>
      (super.noSuchMethod(Invocation.method(#updateTask, [task]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> deleteTask(String? taskID) =>
      (super.noSuchMethod(Invocation.method(#deleteTask, [taskID]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
}
